apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: quorum-validator
  namespace: quorum-network
  labels:
    app: quorum-validator
    component: blockchain
spec:
  serviceName: quorum-validator
  replicas: {{ validators or 4 }}
  selector:
    matchLabels:
      app: quorum-validator
  template:
    metadata:
      labels:
        app: quorum-validator
        component: blockchain
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: besu
        image: hyperledger/besu:latest
        ports:
        - containerPort: 8545
          name: rpc
        - containerPort: 8546
          name: ws
        - containerPort: 30303
          name: p2p
        - containerPort: 9545
          name: metrics
        env:
        - name: BESU_OPTS
          value: "--Xmx2g -Xms2g"
        command:
        - /bin/bash
        - -c
        - |
          /opt/besu/bin/besu \
          --config-file=/etc/quorum/config.toml \
          --p2p-host=$(hostname -i) \
          --node-private-key-file=/etc/quorum/keys/key
        volumeMounts:
        - name: quorum-config
          mountPath: /etc/quorum
          readOnly: true
        - name: quorum-keys
          mountPath: /etc/quorum/keys
          readOnly: true
        - name: data
          mountPath: /opt/besu/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8545
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: quorum-config
        configMap:
          name: quorum-config
      - name: quorum-keys
        secret:
          secretName: quorum-keys
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: managed-premium
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: quorum-validator
  namespace: quorum-network
  labels:
    app: quorum-validator
spec:
  clusterIP: None
  selector:
    app: quorum-validator
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: ws
    port: 8546
    targetPort: 8546
  - name: p2p
    port: 30303
    targetPort: 30303
  - name: metrics
    port: 9545
    targetPort: 9545