apiVersion: apps/v1
kind: Deployment
metadata:
  name: quorum-rpc
  namespace: quorum-network
  labels:
    app: quorum-rpc
    component: rpc-endpoint
spec:
  replicas: {{ rpcNodes or 1 }}
  selector:
    matchLabels:
      app: quorum-rpc
  template:
    metadata:
      labels:
        app: quorum-rpc
        component: rpc-endpoint
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: besu
        image: hyperledger/besu:latest
        ports:
        - containerPort: 8545
          name: rpc
        - containerPort: 8546
          name: ws
        - containerPort: 30303
          name: p2p
        - containerPort: 9545
          name: metrics
        env:
        - name: BESU_OPTS
          value: "--Xmx4g -Xms4g"
        command:
        - /bin/bash
        - -c
        - |
          /opt/besu/bin/besu \
          --config-file=/etc/quorum/config.toml \
          --p2p-host=$(hostname -i) \
          --node-private-key-file=/etc/quorum/keys/rpc-key \
          --bootnodes=enode://validator1@quorum-validator-0.quorum-validator:30303
        volumeMounts:
        - name: quorum-config
          mountPath: /etc/quorum
          readOnly: true
        - name: quorum-keys
          mountPath: /etc/quorum/keys
          readOnly: true
        - name: data
          mountPath: /opt/besu/data
        resources:
          requests:
            memory: "4Gi"
            cpu: "1500m"
          limits:
            memory: "8Gi"
            cpu: "3000m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8545
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8545
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: quorum-config
        configMap:
          name: quorum-config
      - name: quorum-keys
        secret:
          secretName: quorum-keys
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: quorum-rpc
  namespace: quorum-network
  labels:
    app: quorum-rpc
spec:
  selector:
    app: quorum-rpc
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: ws
    port: 8546
    targetPort: 8546
  - name: metrics
    port: 9545
    targetPort: 9545
---
apiVersion: v1
kind: Service
metadata:
  name: quorum-rpc-external
  namespace: quorum-network
  labels:
    app: quorum-rpc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: quorum-rpc
  ports:
  - name: rpc
    port: 8545
    targetPort: 8545
  - name: ws
    port: 8546
    targetPort: 8546