name: Semantic Version & Conventional Commits

on:
  pull_request:
    branches: [ Mistress, main ]
  push:
    branches: [ Mistress ]

jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate commit messages
        run: |
          echo "Validating commit messages..."
          pattern='^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?: .+' \
          ;
          git log --format=%s origin/HEAD..HEAD || true
          while read -r line; do
            [[ -z "$line" ]] && continue
            if ! echo "$line" | grep -Eq "$pattern"; then
              echo "::error::Commit message does not follow Conventional Commits: $line"; exit 1; fi
          done < <(git log --format=%s origin/HEAD..HEAD || true)
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure version in package.json matches tag (on push with tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PKG_VERSION=$(jq -r .version package.json)
          if [ "$TAG" != "v$PKG_VERSION" ]; then
            echo "::error::Tag $TAG does not match package.json version v$PKG_VERSION"; exit 1; fi